'use client'

import { GitHubUser } from '@/types/github'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent } from '@/components/ui/card'

interface ProfileCardProps {
  user: GitHubUser
  topLanguages: string[]
  totalStars: number
  totalRepos: number
}

export function ProfileCard({ user, topLanguages, totalStars, totalRepos }: ProfileCardProps) {
  return (
    <Card className="w-[400px] bg-gradient-to-br from-background to-muted">
      <CardContent className="p-6">
        <div className="flex items-center gap-4">
          <Avatar className="h-16 w-16">
            <AvatarImage src={user.avatar_url} alt={user.login} />
            <AvatarFallback>{user.login[0].toUpperCase()}</AvatarFallback>
          </Avatar>
          
          <div>
            <h3 className="text-xl font-bold">{user.name || user.login}</h3>
            <p className="text-muted-foreground">@{user.login}</p>
          </div>
        </div>
        
        {user.bio && (
          <p className="mt-4 text-sm">{user.bio}</p>
        )}
        
        <div className="mt-4 flex flex-wrap gap-2">
          {topLanguages.slice(0, 3).map((lang) => (
            <Badge key={lang} variant="secondary">{lang}</Badge>
          ))}
        </div>
        
        <div className="mt-4 grid grid-cols-2 gap-4 text-center">
          <div>
            <div className="text-2xl font-bold">{totalRepos}</div>
            <p className="text-xs text-muted-foreground">Repositories</p>
          </div>
          <div>
            <div className="text-2xl font-bold">{totalStars}</div>
            <p className="text-xs text-muted-foreground">Stars</p>
          </div>
        </div>
        
        <div className="mt-4 text-center text-xs text-muted-foreground">
          Generated by Git Insight
        </div>
      </CardContent>
    </Card>
  )
}
